# Generated by Django 2.1.7 on 2020-06-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200625_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
